<?php
$products_url=get_post_type_archive_link('product')?:home_url('/products');
$cart_url=function_exists('wc_get_cart_url')?wc_get_cart_url():home_url('/cart');
$account_url=function_exists('wc_get_page_permalink')?wc_get_page_permalink('myaccount'):home_url('/account');
$login_url=home_url('/login');
$cart_count=class_exists('DMC_Cart')?DMC_Cart::get_item_count():((function_exists('WC')&&WC()->cart)?WC()->cart->get_cart_contents_count():0);
?>
<!doctype html><html <?php language_attributes(); ?>><head><meta charset="<?php bloginfo('charset'); ?>"><meta name="viewport" content="width=device-width, initial-scale=1"><link rel="profile" href="https://gmpg.org/xfn/11"><?php wp_head(); ?></head>
<body <?php body_class(); ?>><?php wp_body_open(); ?>
<header class="site-header" id="marketplace-header">
<div class="utility-bar"><div class="site-container utility-inner"><span><i class="utility-dot"></i> Instant delivery on eligible digital goods</span><span class="utility-spacer"></span><span>Secure checkout</span><span>Verified products</span><span>Support when you need it</span></div></div>
<div class="nav-shell"><div class="site-container main-nav">
<a class="brand" href="<?php echo esc_url(home_url('/')); ?>"><span class="brand-mark"><span></span><span></span><span></span></span><span><strong><?php bloginfo('name'); ?></strong><small>Digital goods marketplace</small></span></a>
<form class="nav-search" id="header-search-form" role="search" method="get" action="<?php echo esc_url(home_url('/')); ?>"><span>⌕</span><input id="nav-search-input" type="search" name="s" value="<?php echo esc_attr(get_search_query()); ?>" placeholder="Search subscriptions, licenses, software…" autocomplete="off"><input type="hidden" name="post_type" value="product"><kbd>Ctrl K</kbd><div class="instant-search-popover" id="header-search-popover" aria-hidden="true" role="listbox"></div></form>
<nav class="primary-nav" aria-label="Primary navigation"><a class="active" href="<?php echo esc_url(home_url('/')); ?>">Home</a><a href="<?php echo esc_url($products_url); ?>">Shop</a><a href="<?php echo esc_url(home_url('/about')); ?>">How it works</a><a href="<?php echo esc_url(home_url('/contact')); ?>">Support</a></nav>
<div class="nav-actions"><button class="icon-btn" id="theme-toggle" type="button" aria-label="Toggle dark mode">☾</button><?php if(is_user_logged_in()): ?><a class="icon-btn" href="<?php echo esc_url($account_url); ?>" aria-label="My account">♙</a><?php else: ?><a class="nav-signin" href="<?php echo esc_url($login_url); ?>">Sign in</a><?php endif; ?><a class="cart-btn" href="<?php echo esc_url($cart_url); ?>"><span>Bag</span><b id="nav-cart-badge"><?php echo esc_html($cart_count); ?></b></a><button class="menu-toggle" id="wp-mobile-menu-toggle" type="button" aria-expanded="false" aria-controls="wp-mobile-nav-panel">☰</button></div>
</div><div class="mobile-nav" id="wp-mobile-nav-panel"><div class="site-container"><form role="search" method="get" action="<?php echo esc_url(home_url('/')); ?>" class="mobile-search"><input type="search" name="s" placeholder="Search digital products…"><input type="hidden" name="post_type" value="product"></form><div class="mobile-links"><a href="<?php echo esc_url(home_url('/')); ?>">Home</a><a href="<?php echo esc_url($products_url); ?>">Shop</a><a href="<?php echo esc_url(home_url('/about')); ?>">How it works</a><a href="<?php echo esc_url(home_url('/contact')); ?>">Support</a><a href="<?php echo esc_url($cart_url); ?>">Cart (<?php echo esc_html($cart_count); ?>)</a><?php if(is_user_logged_in()): ?><a href="<?php echo esc_url($account_url); ?>">My Account</a><?php else: ?><a href="<?php echo esc_url($login_url); ?>">Sign in / Register</a><?php endif; ?></div></div></div></div>
</header><main id="primary" class="site-main">
