<?php
/** Template Name: Login / Signup Page */
get_header(); ?>
<div id="marketplace-auth-page" class="auth-page-wrapper"><div class="site-container">
<?php if(is_user_logged_in()): $current_user=wp_get_current_user(); ?>
<div class="auth-layout"><section class="auth-pitch"><span class="hero-badge"><i></i> Customer account</span><h2>Your digital purchases, together.</h2><p>Keep your orders, eligible downloads and account information in one secure customer area.</p><div class="auth-benefits"><div class="auth-benefit"><i>✓</i><div><strong>Order history</strong><span>Review your previous purchases.</span></div></div><div class="auth-benefit"><i>↯</i><div><strong>Fast access</strong><span>Open eligible digital downloads from your account.</span></div></div><div class="auth-benefit"><i>◉</i><div><strong>Customer support</strong><span>Keep account and order context together.</span></div></div></div></section><section class="auth-form-side"><div class="auth-logged-in-state"><div class="auth-avatar-icon"><span class="auth-user-avatar-badge"><?php echo get_avatar($current_user->ID,58); ?></span></div><h2 class="auth-user-greeting">Welcome back, <?php echo esc_html($current_user->display_name); ?></h2><p class="auth-user-email"><?php echo esc_html($current_user->user_email); ?></p><p class="auth-session-info">Your customer session is active. Continue to your dashboard to manage orders and eligible digital downloads.</p><div class="auth-action-buttons"><a href="<?php echo esc_url(home_url('/account')); ?>" class="btn btn-primary btn-block btn-lg">Open customer dashboard →</a><a href="<?php echo esc_url(wp_logout_url(home_url('/'))); ?>" class="btn btn-secondary btn-block">Sign out</a></div></div></section></div>
<?php else: ?>
<div class="auth-layout"><section class="auth-pitch"><span class="hero-badge"><i></i> Digital goods marketplace</span><h2>Sign in once. Keep every purchase close.</h2><p>Access your orders, subscriptions, licenses and eligible downloads from one clean customer account.</p><div class="auth-benefits"><div class="auth-benefit"><i>✓</i><div><strong>Simple account access</strong><span>Use your WordPress customer account.</span></div></div><div class="auth-benefit"><i>↯</i><div><strong>Digital delivery</strong><span>Find eligible products after checkout.</span></div></div><div class="auth-benefit"><i>◆</i><div><strong>Protected checkout</strong><span>Designed for a secure purchasing journey.</span></div></div></div><div class="auth-visual-card"><small>YOUR DIGITAL COLLECTION</small><strong>Ready to access</strong><div class="auth-visual-lines"><i></i><i></i><i></i></div></div></section><section class="auth-form-side"><div class="auth-header"><span class="auth-badge"><span class="auth-badge-dot"></span> Verified customer access</span><h1 class="auth-title">Welcome back.</h1><p class="auth-subtitle">Sign in to manage your purchases and access eligible digital products.</p></div>
<?php if(isset($_GET['login'])&&'failed'===sanitize_key(wp_unslash($_GET['login']))): ?><div class="auth-alert auth-alert-danger" role="alert">Invalid username or password. Please check your details and try again.</div><?php elseif(isset($_GET['login'])&&'empty'===sanitize_key(wp_unslash($_GET['login']))): ?><div class="auth-alert auth-alert-danger" role="alert">Please enter your username/email address and password.</div><?php elseif(isset($_GET['loggedout'])&&'true'===sanitize_key(wp_unslash($_GET['loggedout']))): ?><div class="auth-alert auth-alert-success" role="status">You have been securely signed out.</div><?php endif; ?>
<div class="auth-form-wrapper"><?php wp_login_form(['echo'=>true,'redirect'=>home_url('/account'),'form_id'=>'marketplace-wp-login-form','label_username'=>'Email or Username','label_password'=>'Password','label_remember'=>'Keep me signed in','label_log_in'=>'Sign in to account →','id_username'=>'user_login','id_password'=>'user_pass','id_remember'=>'rememberme','id_submit'=>'wp-submit','remember'=>true,'value_username'=>'','value_remember'=>true]); ?></div><div class="auth-footer-nav"><?php if(get_option('users_can_register')):?><a href="<?php echo esc_url(wp_registration_url()); ?>">Create an account</a><?php else:?><span class="auth-signup-hint">New customer? An account can be created during checkout.</span><?php endif; ?><a href="<?php echo esc_url(wp_lostpassword_url()); ?>">Forgot password?</a></div><div class="auth-trust-notice"><span class="trust-shield-icon">⌑</span><div><strong>WordPress account security</strong><p>Your login is handled by WordPress authentication and protected by standard session security.</p></div></div></section></div>
<?php endif; ?></div></div><?php get_footer(); ?>
